name: Artifacts native build and upload

on:
  push:
    branches: [ "dev" ]
  release:
    types: [published]

    
defaults:
  run:
    working-directory: schedular

jobs:
  build:
    name: Build artifact ${{ matrix.asset_name }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # - os: ubuntu-latest
          #   asset_name: linux-amd64
          #   executable-suffix: ''
          - os: macos-latest
            asset_name: macos-amd64
            executable-suffix: ''
          # - os: windows-latest
          #   asset_name: windows-amd64
          #   executable-suffix: '.exe'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: latest
          java-version: '21'
          distribution: 'graalvm'
          components: native-image
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build artifact
        run: ./mvnw clean package -DskipTests=true #./mvnw -Pnative native:compile -DskipTests=true
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.os }}-${{ matrix.asset_name }}
          path: ${{ github.workspace }}/schedular/target/
          overwrite: true